/* HALL VISITS */
SELECT
	EVENTS.ID
	,EVENTS.CREATED_AT
	,'HALL' AS DATA_TYPE
	,HALLS.NAME
	,SFC.FIRSTNAME
	,SFC.LASTNAME
	,SFC.COMPANY
	,SFC.CUSTOMERID
	,SFC.EMAIL AS USER_EMAIL
	,SFC.PHONE_WORK
FROM 
	ETR_EVENT_LOGHRCOM EVENTS
LEFT JOIN
	SF_CUSTOMERHRCOM SFC
ON
	EVENTS.INITIATOR_ID = SFC.CUSTOMERID
LEFT JOIN
	TRADESHOW_HALLHRCOM HALLS
ON
	HALLS.ID = EVENTS.TARGET_ID
WHERE
	HALLS.SHOW_ID = 1629319409551
	AND YYYYMMDD >= '20211114';
	

/* LOUNGES */
SELECT
	EVENTS.ID
	,EVENTS.CREATED_AT
	,'LOUNGE' AS DATA_TYPE
	,LOUNGES.NAME
	,SFC.FIRSTNAME
	,SFC.LASTNAME
	,SFC.COMPANY
	,SFC.CUSTOMERID
	,SFC.EMAIL AS USER_EMAIL
	,SFC.PHONE_WORK
FROM 
	ETR_EVENT_LOGHRCOM EVENTS
LEFT JOIN
	SF_CUSTOMERHRCOM SFC
ON
	EVENTS.INITIATOR_ID = SFC.CUSTOMERID
LEFT JOIN
	TRADESHOW_LOUNGEHRCOM LOUNGES
ON
	LOUNGES.ID = EVENTS.TARGET_ID
WHERE
	LOUNGES.SHOW_ID = 1629319409551
	AND YYYYMMDD >= '20211114';